apiVersion: v1
kind: Pod
metadata:
  labels:
    run: girus
    service: webserver
  name: girus
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {} # colocar limitadores de recursos
  - image: busybox
    name: busybox
    args:
    - sleep
    - "600"
  dnsPolicy: ClusterFirst # como resolve o dns, nesse caso resolve primeiro do cluster
  restartPolicy: Always # restar o pod se tiver algum problema
status: {}
